#pragma warning disable 0649
//This script is generated by jhg's DataGenerator.

using Newtonsoft.Json;

public struct DataAnimal : IBaseData
{
    [JsonProperty(PropertyName = "id")]
    private readonly int id;
    [JsonProperty(PropertyName = "nameId")]
    private readonly string nameId;
    [JsonProperty(PropertyName = "AnimalType")]
    public readonly AnimalType AnimalType;
	
	public int Id => id;
    public string NameId => nameId;
    public bool IsInit => id == 0;
}
